name: Publish to pub.dev
on:
  push:
    tags:
      - rel/*
jobs:
  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
      - name: Setup Credentials
        shell: bash
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          sh ./prepublish.sh
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Publish Package
        run: dart pub publish -f
